# making the nested call fine to use, where `tflite.tflite` IS-A `tflite`.
from . import tflite

########################## BELOW ARE AUTO-GENERATED ##########################
from .tflite.SubGraph import *
from .tflite.SoftmaxOptions import *
from .tflite.SquaredDifferenceOptions import *
from .tflite.LogSoftmaxOptions import *
from .tflite.L2NormOptions import *
from .tflite.ArgMaxOptions import *
from .tflite.SubOptions import *
from .tflite.LSHProjectionType import *
from .tflite.LeakyReluOptions import *
from .tflite.ActivationFunctionType import *
from .tflite.CallOptions import *
from .tflite.GatherOptions import *
from .tflite.LessEqualOptions import *
from .tflite.SelectOptions import *
from .tflite.NotEqualOptions import *
from .tflite.Padding import *
from .tflite.MulOptions import *
from .tflite.Tensor import *
from .tflite.LSTMOptions import *
from .tflite.SliceOptions import *
from .tflite.SqueezeOptions import *
from .tflite.FloorDivOptions import *
from .tflite.UnpackOptions import *
from .tflite.ConcatEmbeddingsOptions import *
from .tflite.OneHotOptions import *
from .tflite.SpaceToDepthOptions import *
from .tflite.ReverseV2Options import *
from .tflite.MatrixDiagOptions import *
from .tflite.GreaterOptions import *
from .tflite.IfOptions import *
from .tflite.BuiltinOptions import *
from .tflite.SkipGramOptions import *
from .tflite.MirrorPadOptions import *
from .tflite.SplitOptions import *
from .tflite.SquareOptions import *
from .tflite.BuiltinOperator import *
from .tflite.LessOptions import *
from .tflite.RangeOptions import *
from .tflite.CustomOptionsFormat import *
from .tflite.TransposeOptions import *
from .tflite.MirrorPadMode import *
from .tflite.WhileOptions import *
from .tflite.ReverseSequenceOptions import *
from .tflite.UniqueOptions import *
from .tflite.DepthToSpaceOptions import *
from .tflite.ReducerOptions import *
from .tflite.LogicalAndOptions import *
from .tflite.OperatorCode import *
from .tflite.LSTMKernelType import *
from .tflite.FloorModOptions import *
from .tflite.PowOptions import *
from .tflite.CastOptions import *
from .tflite.QuantizeOptions import *
from .tflite.SequenceRNNOptions import *
from .tflite.CustomQuantization import *
from .tflite.PadV2Options import *
from .tflite.CosOptions import *
from .tflite.EmbeddingLookupSparseOptions import *
from .tflite.ResizeNearestNeighborOptions import *
from .tflite.GreaterEqualOptions import *
from .tflite.FakeQuantOptions import *
from .tflite.BidirectionalSequenceRNNOptions import *
from .tflite.Pool2DOptions import *
from .tflite.Metadata import *
from .tflite.LSHProjectionOptions import *
from .tflite.FillOptions import *
from .tflite.WhereOptions import *
from .tflite.ReshapeOptions import *
from .tflite.MatrixSetDiagOptions import *
from .tflite.ExpOptions import *
from .tflite.SplitVOptions import *
from .tflite.QuantizationParameters import *
from .tflite.MaximumMinimumOptions import *
from .tflite.TransposeConvOptions import *
from .tflite.HardSwishOptions import *
from .tflite.ArgMinOptions import *
from .tflite.LogicalNotOptions import *
from .tflite.DequantizeOptions import *
from .tflite.StridedSliceOptions import *
from .tflite.TileOptions import *
from .tflite.ResizeBilinearOptions import *
from .tflite.CombinerType import *
from .tflite.TensorType import *
from .tflite.AddNOptions import *
from .tflite.PackOptions import *
from .tflite.DepthwiseConv2DOptions import *
from .tflite.Conv2DOptions import *
from .tflite.SpaceToBatchNDOptions import *
from .tflite.AddOptions import *
from .tflite.LocalResponseNormalizationOptions import *
from .tflite.ShapeOptions import *
from .tflite.RNNOptions import *
from .tflite.ConcatenationOptions import *
from .tflite.BidirectionalSequenceLSTMOptions import *
from .tflite.NegOptions import *
from .tflite.BatchToSpaceNDOptions import *
from .tflite.TopKV2Options import *
from .tflite.ExpandDimsOptions import *
from .tflite.QuantizationDetails import *
from .tflite.DivOptions import *
from .tflite.FullyConnectedOptionsWeightsFormat import *
from .tflite.ZerosLikeOptions import *
from .tflite.FullyConnectedOptions import *
from .tflite.EqualOptions import *
from .tflite.GatherNdOptions import *
from .tflite.UnidirectionalSequenceLSTMOptions import *
from .tflite.AbsOptions import *
from .tflite.Model import *
from .tflite.PadOptions import *
from .tflite.Operator import *
from .tflite.RankOptions import *
from .tflite.LogicalOrOptions import *
from .tflite.Buffer import *
from .tflite.SVDFOptions import *
from .tflite.SparseToDenseOptions import *
########################## ABOVE ARE AUTO-GENERATED ##########################
